CREATE TABLE [dbo].[Movie]
(
	[Id] INT NOT NULL IDENTITY,
	[Title] NVARCHAR(200) NOT NULL,
	[Director] NVARCHAR(100) NOT NULL,
	[Synopsis] NVARCHAR(100) NOT NULL,
	[Release] DATETIME NOT NULL,
	CONSTRAINT UK_MOVIE_TITLE_RELEASE UNIQUE ([Title], [Release]),
	CONSTRAINT CK_MOVIE_RELEASE CHECK (YEAR([Release]) >= 1895),
	CONSTRAINT PK_MOVIE_ID PRIMARY KEY ([Id])

)
