CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL IDENTITY,
    [LastName] NVARCHAR(100) NULL,
    [FirstName] NVARCHAR(100) NULL,
    [Email] NVARCHAR(200) NOT NULL,
    [Password] NVARCHAR(200) NOT NULL,
    [Role] TINYINT NOT NULL,
    CONSTRAINT UK_USER_EMAIL UNIQUE ([Email]),
    CONSTRAINT CK_USER_EMAIL CHECK ([Email] LIKE '%@%.%'),
    CONSTRAINT CK_USER_ROLE CHECK ([Role] IN (0,1,2)),
    CONSTRAINT PK_USER_ID PRIMARY KEY ([Id])

)
